apiVersion: v1
kind: ServiceAccount
metadata:
  name: avp-authorizer
  namespace: istio-system
---
apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: istio-system
type: Opaque
data:
  AWS_ACCESS_KEY_ID: <base64-encoded-access-key>
  AWS_SECRET_ACCESS_KEY: <base64-encoded-secret-key>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: avp-authorizer
  namespace: istio-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: avp-authorizer
  template:
    metadata:
      labels:
        app: avp-authorizer
    spec:
      serviceAccountName: avp-authorizer
      containers:
      - name: avp-authorizer
        image: <your-registry>/envoy-avp-authorizer:latest
        args:
        - --region
        - us-east-1
        - --policy-store-id
        - <your-policy-store-id>
        ports:
        - containerPort: 50051
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: AWS_SECRET_ACCESS_KEY
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: avp-authorizer
  namespace: istio-system
spec:
  ports:
  - port: 50051
    name: grpc
  selector:
    app: avp-authorizer